app = 'macrodash-server'
primary_region = 'lax'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[env]
  PORT = "8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1